export const PATIENT_EVENT = {
    GET_PATIENT : 'GET_PATIENT',
    GET_PATIENT_PENDING: 'GET_PATIENT_PENDING',
    GET_PATIENT_FULFILLED: 'GET_PATIENT_FULFILLED',
    GET_PATIENT_REJECTED: 'GET_PATIENT_REJECTED'
};